<!DOCTYPE html>

<article>
    <h2> Article </h2>
    <p>
      THIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENTTHIS IS NEW CONTENT
    </p>
</article>
